export const colors = {
  primary: '#14B8A6',
  primaryDark: '#0D9488',
  primaryLight: '#5EEAD4',
  primarySubtle: '#CCFBF1',
  secondary: '#F59E0B',
  secondaryDark: '#D97706',
  secondaryLight: '#FCD34D',
  accent: '#6366F1',
  accentDark: '#4F46E5',
  backgroundLight: '#FAFAF9',
  backgroundDark: '#1C1917',
  surfaceLight: '#FFFFFF',
  surfaceDark: '#292524',
  surfaceVariantLight: '#F5F5F4',
  surfaceVariantDark: '#44403C',
  textLight: '#1C1917',
  textDark: '#FAFAF9',
  textSecondary: '#78716C',
  textTertiary: '#A8A29E',
  borderLight: '#E7E5E4',
  borderDark: '#57534E',
  success: '#10B981',
  warning: '#F59E0B',
  error: '#EF4444',
  info: '#3B82F6',
  income: '#10B981',
  expense: '#EF4444',
  neutral: '#6366F1',
};

export const theme = {
  light: {
    background: colors.backgroundLight,
    surface: colors.surfaceLight,
    surfaceVariant: colors.surfaceVariantLight,
    text: colors.textLight,
    border: colors.borderLight,
  },
  dark: {
    background: colors.backgroundDark,
    surface: colors.surfaceDark,
    surfaceVariant: colors.surfaceVariantDark,
    text: colors.textDark,
    border: colors.borderDark,
  },
};
